node.name: coordinator6
node.master: true
node.data: false
node.ingest: true
node.attr.zone: spot

cluster.name: ActiveData-es6

cluster.routing.allocation.awareness.attributes: zone
cluster.routing.allocation.enable: none
cluster.routing.allocation.cluster_concurrent_rebalance: 1
cluster.routing.allocation.node_concurrent_recoveries: 1

thread_pool.bulk.queue_size: 3000
thread_pool.index.queue_size: 1000

indices.recovery.max_bytes_per_sec: 1000mb

script.painless.regex.enabled: true
script.max_compilations_rate: 10000/1m

bootstrap.memory_lock: true
path.data: /data1
path.logs: /data1/logs

discovery.ec2.endpoint: ec2.us-west-2.amazonaws.com
discovery.zen.hosts_provider: ec2
discovery.zen.minimum_master_nodes: 1

http.compression: true
http.cors.enabled: true
http.cors.allow-origin: "*"
http.max_content_length: 1000mb

network.host : _site_, _local_
