language: python
python:
  - "2.7"

branches:
  only:
  - master
  - dev
  - merge

env:
  global:
      - PYTHONPATH=.
      - ES_VERSION=1.7.5
      - ES_DOWNLOAD_URL=https://download.elastic.co/elasticsearch/elasticsearch/elasticsearch-${ES_VERSION}.tar.gz

install:
  - "wget ${ES_DOWNLOAD_URL}"
  - "tar -xzf elasticsearch-${ES_VERSION}.tar.gz"
  - "sudo cp -f tests/travis/elasticsearch.yml /etc/elasticsearch/elasticsearch.yml"
  - "./elasticsearch-${ES_VERSION}/bin/elasticsearch &"
  - "pip install -r requirements.txt"
  - "wget -q --waitretry=1 --retry-connrefused -T 10 -O - http://127.0.0.1:9200"

# command to run tests
script:
  - tests/travis/run.sh
